
GET http://localhost:4000/health

###

GET http://localhost:4000

###

GET http://localhost:4000/api/v1/tickets

###

POST http://localhost:4000/api/v1/tickets
Content-Type: application/json

{
  "username": "masud",
  "price": 20
}

###

POST http://localhost:4000/api/v1/tickets/bulk
Content-Type: application/json

{
  "username": "abdullah",
  "price": 15,
  "quantity": 7
}

###

GET http://localhost:4000/api/v1/tickets/t/xxLC96Lt_7

###

GET http://localhost:4000/api/v1/tickets/u/abdullah

###

DELETE http://localhost:4000/api/v1/tickets/t/xxLC96Lt_7

###

DELETE http://localhost:4000/api/v1/tickets/u/masud

###

PUT http://localhost:4000/api/v1/tickets/t/0aTVCdlFp
Content-Type: application/json

{"username": "masud"}

###

PUT http://localhost:4000/api/v1/tickets/u/abdullah
Content-Type: application/json

{"price": 12}

###

GET http://localhost:4000/api/v1/tickets/draw