GET http://localhost:4000/health

###

GET http://localhost:4000/api/v1/tickets

###

POST http://localhost:4000/api/v1/tickets
Content-Type: application/json

{
  "username": "mamun",
  "price": 20
}

###

POST http://localhost:4000/api/v1/tickets/bulk
Content-Type: application/json

{
  "username": "abdullah",
  "price": 15,
  "quantity": 2
}

###

GET http://localhost:4000/api/v1/tickets/t/Lxk1RYTHO

###

GET http://localhost:4000/api/v1/tickets/u/abdullah

###

DELETE http://localhost:4000/api/v1/tickets/t/HbRFOfX5k

###

DELETE http://localhost:4000/api/v1/tickets/u/abdullah

###

PUT http://localhost:4000/api/v1/tickets/t/1j1cvj7L3
Content-Type: application/json

{"username": "masud", "price": 25}

###

PUT http://localhost:4000/api/v1/tickets/u/masud
Content-Type: application/json

{"username": "abdullah"}

###

GET http://localhost:4000/api/v1/tickets/draw?wc=2